name: youth_bridge
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.2
  custom_circular_progress: ^1.0.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  curved_navigation_bar: ^1.0.3
  cloud_firestore: ^4.15.8
  http: ^1.2.0
  html: ^0.15.4
  image_picker: ^1.0.8
  intl: ^0.19.0
  video_player: ^2.8.5
  table_calendar: ^3.1.1
  scrollable_positioned_list: ^0.3.8
  provider: ^6.0.0
  carousel_slider: ^4.2.1
  firebase_storage: ^11.6.9
  uuid: ^4.4.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/splash1.png
    - assets/img/logo_white.png
